# ----------------------------
# Makefile Options
# ----------------------------

NAME = DEMO
ICON = icon.png
DESCRIPTION = "gfx3 Demo"
COMPRESSED = YES
ARCHIVED = NO

# ----------------------------
# Debugging
# ----------------------------

HAS_PRINTF = NO

# ----------------------------

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
