# ----------------------------
# Program Options
# ----------------------------

NAME         ?= GFX3
ICON         ?= icon.png
DESCRIPTION  ?= "GFX3 TEST"
COMPRESSED   ?= YES
ARCHIVED     ?= NO

CFLAGS ?= -Wall -Wextra -Oz
CXXFLAGS ?= -Wall -Wextra -Oz

# ----------------------------

ifndef CEDEV
$(error CEDEV environment path variable is not set)
endif

include $(CEDEV)/meta/makefile.mk

